# Setup
title:    D.A.O.O.
tagline:  Diseño Avanzado Orientado a Objetos
baseurl:
github:   https://github.com/FacultadDeIngenieria/daoo
zip:	    https://github.com/FacultadDeIngenieria/daoo/zipball/master

# About/contact
author:
name:       Diseño y Programación Orientado a Internet
url:
